#! /usr/bin/python  

import cgi, cgitb
import json
import requests

print "Content-type: text/html\n\n"	
print "Hello, World."

def get_post_data():
	form = cgi.FieldStorage()
	index = 2
	index = form['index'].value
	text = 3
	text = form['text'].value
	return (index, text)


def update_json(index, text):
	try:
		inputFile = open("../description.json")
		inputData = json.load(inputFile)
		print inputData["name"]
	except IOError as e:
		print "I/O error({0}): {1}". format(e.errno, e.strerror)
		exit()
	except ValueError:
		print "JSON format is incorrect. Please correct and try again!"
		exit()
	print inputData["desc"][index]

	
(index, text) = get_post_data()
print index
print text
update_json("index", "text")
# get_post_data()